---
version: "3.9"
services:
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nginx/:/etc/nginx:ro
      - ./docker/nginx/log:/var/log/nginx
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: isucon2021_prior
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      MYSQL_ROOT_PASSWORD: isucon
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    healthcheck:
      test: mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD
  app:
    build:
      context: .
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: isucon
    entrypoint:
      - /dockerize
      - -wait
      - tcp://mysql:3306
    command:
      - /app/main
    ports:
      - 9292:9292
    links:
      - mysql
    volumes:
      - ./public:/public
    depends_on:
      - mysql
